# Generated by Django 3.2.2 on 2021-05-12 23:57

import django.utils.timezone
import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_leads", models.BooleanField(default=False)),
                ("has_tasks", models.BooleanField(default=True)),
                ("has_notes", models.BooleanField(default=True)),
                ("has_chat", models.BooleanField(default=True)),
                ("is_student", models.BooleanField(default=False)),
                ("is_teacher", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=20, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pronouns",
                    models.CharField(
                        choices=[
                            ("H", "He/Him His, Himself"),
                            ("S", "She/Her Hers, Herself"),
                            ("T", "They/Them Theirs, themself"),
                            ("Z", "Ze (or Zie or Xe)\tZee (like “see” with a “Z”)"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="default.webp", upload_to="profile_pics"),
                ),
                ("headline", models.CharField(blank=True, max_length=50, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("rejected", models.DateTimeField(blank=True, null=True)),
                ("viewed", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_req_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_req_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
