# Generated by Django 3.2.2 on 2021-05-07 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_leads", models.BooleanField(default=False)),
                ("has_tasks", models.BooleanField(default=True)),
                ("has_notes", models.BooleanField(default=True)),
                ("has_chat", models.BooleanField(default=True)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(default="default.webp", upload_to="profile_pics"),
                ),
                ("headline", models.CharField(blank=True, max_length=50, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
