# Generated by Django 3.2.2 on 2021-05-07 18:52

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
