# Generated by Django 3.2.2 on 2021-05-07 18:56

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
