# Generated by Django 3.2.2 on 2021-05-07 19:38

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(
                choices=[
                    ("H", "He/Him His, Himself"),
                    ("S", "She/Her Hers, Herself"),
                    ("T", "They/Them Theirs, themself"),
                    ("Z", "Ze (or Zie or Xe)\tZee (like “see” with a “Z”)"),
                ],
                default="T",
                max_length=1,
            ),
        ),
    ]
