# Generated by Django 3.1.7 on 2021-05-07 21:59

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
