# Generated by Django 3.2 on 2021-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
