# Generated by Django 3.2.2 on 2021-05-07 22:00

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210507_2159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
