# Generated by Django 3.2.2 on 2021-05-07 23:01

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_lead_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("APP", "Applied for position"),
                    ("INT", "Interview with organization"),
                    ("NOT", "Involuntary No Further Consideration"),
                    ("ACT", "Offer Extended, Accepted"),
                    ("DCL", "Offer Extended, Voluntarily withdrawl"),
                    ("WDW", "Voluntary Candidancy Withdrawl"),
                    ("DNY", "Involuntary Candidancy Withdrawl"),
                ],
                default="APP",
                max_length=3,
            ),
        ),
    ]
