/** @format */

export const userList = [
  {
    id: 1,
    user: {
      id: 4,
      password:
        "pbkdf2_sha256$260000$eao6SXVeP5XEhq7HcjbB8s$rsmMZcZWY1ugSmN/NJBi4dyVuSBWCAgWhJIPkQppCto=",
      last_login: "2021-05-07T23:20:10Z",
      is_superuser: false,
      username: "cardi.b",
      first_name: "cardi",
      last_name: "",
      email: "cardib@cardib.com",
      is_staff: false,
      is_active: true,
      date_joined: "2021-05-07T23:19:20Z",
      groups: [],
      user_permissions: [],
    },
    has_leads: false,
    has_tasks: true,
    has_notes: true,
    has_chat: true,
    is_student: false,
    is_teacher: false,
    location: null,
    middle_name: null,
    pronouns: "T",
    birthdate: null,
    image: "http://127.0.0.1:8000/media/profile_pics/fire-wallpaper-207353.jpg",
    headline: null,
    bio: "",
    friends: [],
  },
  {
    id: 2,
    user: {
      id: 5,
      password:
        "pbkdf2_sha256$260000$U984d8p4JEoiluBs7qe53s$GDluoZkfGYT0aWwMBGxFFLf/uFBGnGLHpNGtun1k1Lc=",
      last_login: "2021-05-10T23:02:08.853636Z",
      is_superuser: true,
      username: "genryusai.shigekuni.yamamoto",
      first_name: "Genryūsai",
      last_name: "Yamamoto",
      email: "genryusai.shigekuni.yamamoto@soulsociety.com",
      is_staff: true,
      is_active: true,
      date_joined: "2021-05-10T22:35:09Z",
      groups: [],
      user_permissions: [],
    },
    has_leads: false,
    has_tasks: true,
    has_notes: true,
    has_chat: true,
    is_student: false,
    is_teacher: false,
    location: null,
    middle_name: "Shigekuni",
    pronouns: "T",
    birthdate: null,
    image:
      "http://127.0.0.1:8000/media/profile_pics/genryusai.shigekuni.yamamoto.png",
    headline: null,
    bio: "",
    friends: [],
  },
];
