# Generated by Django 3.1.7 on 2021-03-15 05:40

from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=70, null=True)),
                ("note_body", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
                ("date_published", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Archive Note"),
                            ("D", "Note is soft deleted"),
                            ("U", "Unread Note"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, default=str, max_length=200, null=True
                    ),
                ),
                ("mentions", models.JSONField(blank=True, default=dict, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
