users = User.objects.filter(is_superuser=False, is_staff=False)
for user in users:
    user.set_password("password123!@#")
    user.save()
    user = get_object_or_404(User, pk=user_id) 
User.objects.create_user(is_superuser= True, username =  "admin1", first_name= "", last_name= "", email= "", is_staff= True, is_active= True,)
User.objects.create_user(is_superuser= True, username =  "admin2", first_name= "", last_name= "", email= "", is_staff= True, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "testuser2", first_name= "John", last_name= "Doe", email= "john.d.doe@example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "testuser3", first_name= "Jane", last_name= "Doe", email= "jane.d.doe@example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Eddard.Stark", first_name= "Eddard", last_name= "Stark", email= "Eddard.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Robert.Baratheon", first_name= "Robert", last_name= "Baratheon", email= "Robert.Baratheon@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Jaime.Lannister", first_name= "Jaime", last_name= "Lannister", email= "Jaime.Lannister@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Catelyn.Stark", first_name= "Catelyn", last_name= "Stark", email= "Catelyn.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Cersei.Lannister", first_name= "Cersei", last_name= "Lannister", email= "Cersei.Lannister@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Daenerys.Targaryen", first_name= "Daenerys", last_name= "Targaryen", email= "Daenerys.Targaryen@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Jorah.Mormont", first_name= "Jorah", last_name= "Mormont", email= "Jorah.Mormont@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Viserys.Targaryen", first_name= "Viserys", last_name= "Targaryen", email= "Viserys.Targaryen@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Jon.Snow", first_name= "Jon", last_name= "Snow", email= "Jon.Snow@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Robb.Stark", first_name= "Robb", last_name= "Stark", email= "Robb.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Sansa.Stark", first_name= "Sansa", last_name= "Stark", email= "Sansa.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Arya.Stark", first_name= "Arya", last_name= "Stark", email= "Arya.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Theon.Greyjoy", first_name= "Theon", last_name= "Greyjoy", email= "Theon.Greyjoy@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Brandon.Stark", first_name= "Brandon", last_name= "Stark", email= "Brandon.Stark@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Joffrey.Baratheon", first_name= "Joffrey", last_name= "Baratheon", email= "Joffrey.Baratheon@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Sandor.Clegane", first_name= "Sandor", last_name= "Clegane", email= "Sandor.Clegane@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Tyrion.Lannister", first_name= "Tyrion", last_name= "Lannister", email= "Tyrion.Lannister@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Petyr.Baelish", first_name= "Petyr", last_name= "Baelish", email= "Petyr.Baelish@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Davos.Seaworth", first_name= "Davos", last_name= "Seaworth", email= "Davos.Seaworth@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Samwell.Tarly", first_name= "Samwell", last_name= "Tarly", email= "Samwell.Tarly@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Stannis.Baratheon", first_name= "Stannis", last_name= "Baratheon", email= "Stannis.Baratheon@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Jeor.Mormont", first_name= "Jeor", last_name= "Mormont", email= "Jeor.Mormont@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Margaery.Tyrell", first_name= "Margaery", last_name= "Tyrell", email= "Margaery.Tyrell@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Tywin.Lannister", first_name= "Tywin", last_name= "Lannister", email= "Tywin.Lannister@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Talisa.Maegyr", first_name= "Talisa", last_name= "Maegyr", email= "Talisa.Maegyr@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Tormund.Giantsbane", first_name= "Tormund", last_name= "Giantsbane", email= "Tormund.Giantsbane@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Brienne.DeTarth", first_name= "Brienne", last_name= "DeTarth", email= "Brienne.DeTarth@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Ramsay.Bolton", first_name= "Ramsay", last_name= "Bolton", email= "Ramsay.Bolton@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Daario.Naharis", first_name= "Daario", last_name= "Naharis", email= "Daario.Naharis@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Ellaria.Sand", first_name= "Ellaria", last_name= "Sand", email= "Ellaria.Sand@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Tommen.Baratheon", first_name= "Tommen", last_name= "Baratheon", email= "Tommen.Baratheon@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Jaqen.H'ghar", first_name= "Jaqen", last_name= "H'ghar", email= "Jaqen.H'ghar@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Roose.Bolton", first_name= "Roose", last_name= "Bolton", email= "Roose.Bolton@game_of_thrones.example.com", is_staff= False, is_active= True,)
User.objects.create_user(is_superuser= False, username =  "Grey.Worm", first_name= "Grey", last_name= "Worm", email= "Grey.Worm@game_of_thrones.example.com", is_staff= False, is_active= True,)
